/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnnouncementSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'createdByUserId', 'endsAt', 'id', 'isActive', 'position', 'startsAt', 'title', 'updatedAt', 'variant'] as const
  $columns = AnnouncementSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare position: number
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variant: string
}

export class AttachmentSchema extends BaseModel {
  static $columns = ['attachableId', 'attachableType', 'createdAt', 'filename', 'id', 'mimeType', 'path', 'size', 'updatedAt', 'uploadedByUserId'] as const
  $columns = AttachmentSchema.$columns
  @column()
  declare attachableId: number
  @column()
  declare attachableType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filename: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string | null
  @column()
  declare path: string
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedByUserId: number | null
}

export class BranchSchema extends BaseModel {
  static $columns = ['address', 'city', 'companyId', 'country', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = BranchSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare companyId: number
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'phone', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GroupTicketSchema extends BaseModel {
  static $columns = ['groupId', 'id', 'ticketId'] as const
  $columns = GroupTicketSchema.$columns
  @column()
  declare groupId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ticketId: number
}

export class GroupSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = GroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MailServiceAccountSchema extends BaseModel {
  static $columns = ['accessToken', 'connectedByUserId', 'createdAt', 'displayName', 'email', 'id', 'lastError', 'lastSyncedAt', 'microsoftTenantId', 'microsoftUserId', 'provider', 'refreshToken', 'scopes', 'tokenExpiresAt', 'updatedAt', 'webhookClientState'] as const
  $columns = MailServiceAccountSchema.$columns
  @column()
  declare accessToken: string
  @column()
  declare connectedByUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare microsoftTenantId: string
  @column()
  declare microsoftUserId: string
  @column()
  declare provider: string
  @column()
  declare refreshToken: string
  @column()
  declare scopes: string | null
  @column.dateTime()
  declare tokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare webhookClientState: string
}

export class MailServiceFolderSchema extends BaseModel {
  static $columns = ['createdAt', 'deltaLink', 'displayName', 'graphFolderId', 'id', 'isEnabled', 'lastError', 'lastSyncedAt', 'mailServiceAccountId', 'parentGraphFolderId', 'subscriptionExpiresAt', 'subscriptionId', 'updatedAt', 'wellKnownName'] as const
  $columns = MailServiceFolderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deltaLink: string | null
  @column()
  declare displayName: string
  @column()
  declare graphFolderId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isEnabled: boolean
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare mailServiceAccountId: number
  @column()
  declare parentGraphFolderId: string | null
  @column.dateTime()
  declare subscriptionExpiresAt: DateTime | null
  @column()
  declare subscriptionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wellKnownName: string | null
}

export class MailServiceMessageSchema extends BaseModel {
  static $columns = ['conversationId', 'createdAt', 'graphMessageId', 'id', 'internetMessageId', 'mailServiceAccountId', 'mailServiceFolderId', 'receivedAt', 'senderEmail', 'subject', 'ticketId', 'updatedAt'] as const
  $columns = MailServiceMessageSchema.$columns
  @column()
  declare conversationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare graphMessageId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare internetMessageId: string | null
  @column()
  declare mailServiceAccountId: number
  @column()
  declare mailServiceFolderId: number | null
  @column.dateTime()
  declare receivedAt: DateTime | null
  @column()
  declare senderEmail: string | null
  @column()
  declare subject: string | null
  @column()
  declare ticketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrioritySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'level', 'name', 'slug', 'updatedAt'] as const
  $columns = PrioritySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StatusSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'position', 'slug', 'updatedAt'] as const
  $columns = StatusSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketEventSchema extends BaseModel {
  static $columns = ['actorUserId', 'createdAt', 'description', 'eventType', 'id', 'metadata', 'ticketId'] as const
  $columns = TicketEventSchema.$columns
  @column()
  declare actorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare ticketId: number
}

export class TicketSatisfactionSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'id', 'rating', 'submittedByUserId', 'technicianId', 'ticketId', 'updatedAt'] as const
  $columns = TicketSatisfactionSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number
  @column()
  declare submittedByUserId: number
  @column()
  declare technicianId: number
  @column()
  declare ticketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketUserSchema extends BaseModel {
  static $columns = ['assignedAt', 'id', 'ticketId', 'userId'] as const
  $columns = TicketUserSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ticketId: number
  @column()
  declare userId: number
}

export class TicketSchema extends BaseModel {
  static $columns = ['categoryId', 'closeConfirmationSentAt', 'closeConfirmationToken', 'closedAt', 'createdAt', 'createdByUserId', 'description', 'id', 'issuerId', 'issuerType', 'parentTicketId', 'priorityId', 'resolvedAt', 'satisfactionRequestedAt', 'satisfactionSubmittedAt', 'satisfactionToken', 'statusId', 'title', 'updatedAt'] as const
  $columns = TicketSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime()
  declare closeConfirmationSentAt: DateTime | null
  @column()
  declare closeConfirmationToken: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare issuerId: number
  @column()
  declare issuerType: string
  @column()
  declare parentTicketId: number | null
  @column()
  declare priorityId: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column.dateTime()
  declare satisfactionRequestedAt: DateTime | null
  @column.dateTime()
  declare satisfactionSubmittedAt: DateTime | null
  @column()
  declare satisfactionToken: string | null
  @column()
  declare statusId: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'email', 'fullName', 'id', 'password', 'role', 'type', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare branchId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
